name: Deploy (Middleman)

on:
  workflow_dispatch:
  push:
    branches: [main]  
    paths:
      - "source/**"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Deploy
        run: _scripts/deploy.sh
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_ACTOR: ${{ github.actor }}
          SITE_LOCATION: '.'
          BUILD_LOCATION: 'build'
          REMOTE_BRANCH: 'gh-pages'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
