# https://github.com/ministryofjustice/hmpps-tech-docs/blob/main/.github/workflows/publish.yml
# https://raw.githubusercontent.com/ministryofjustice/hmpps-tech-docs/main/.github/workflows/publish.yml

name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "source/**"

permissions:
  # actions: read|write|none
  # checks: read|write|none
  # contents: read|write|none
  # deployments: read|write|none
  # id-token: read|write|none
  # issues: read|write|none
  # discussions: read|write|none
  # packages: read|write|none
  # pages: read|write|none
  # pull-requests: read|write|none
  # repository-projects: read|write|none
  # security-events: read|write|none
  # statuses: read|write|none
  contents: write
  pages: write

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: ministryofjustice/cloud-platform-tech-docs-publisher:1.6
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up 💎 Ruby 3.2.0
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.0
        # bundler-cache: true
    
    - name: Build
      run: _scripts/moj/build.sh
    
    # - name: Link checker
    #   run: _scripts/moj/check.sh
    
    - name: Publish site
      run: _scripts/moj/publish.sh